### ISSUE TITLE
RN 0.72.1 use_framework patch for this module for IOS.

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-svg#2082]
I am getting an error finding RCTImagePrimitivesConversions.h

```
Compiling RNSVGImage.mm

❌  /Users/bill_1/theclub/TheClub/node_modules/react-native-svg/apple/Elements/RNSVGImage.mm:36:9: 'react/renderer/imagemanager/RCTImagePrimitivesConversions.h' file not found

#import <react/renderer/imagemanager/RCTImagePrimitivesConversions.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


```

**Comment by billnbell** [comment]
The file is pretty low under `react/renderer/imagemanager/platform/ios/react/renderer/imagemanager/RCTImagePrimitivesConversions.h`

I did try using that and it does not find it either.

**Comment by billnbell** [comment]
they recommend adding React-ImageManager as a pod.

But I am unsure how to reference it?

```
❌  /Users/bill_1/theclub/TheClub/node_modules/react-native-svg/apple/Elements/RNSVGImage.mm:36:9: 'React-ImageManager/RCTImagePrimitivesConversions.h' file not found

#import <React-ImageManager/RCTImagePrimitivesConversions.h>
```

**Comment by billnbell** [comment]
OK I got SVG to work with `use_frameworks! :linkage => :static`

```
react-native-svg+13.9.0.patch
```

And the actual file:

```
diff --git a/node_modules/react-native-svg/RNSVG.podspec b/node_modules/react-native-svg/RNSVG.podspec
index afd13a1..8360f97 100644
--- a/node_modules/react-native-svg/RNSVG.podspec
+++ b/node_modules/react-native-svg/RNSVG.podspec
@@ -13,6 +13,7 @@ Pod::Spec.new do |s|
   s.authors           = 'Horcrux Chen'
   s.platforms         = { :osx => "10.14", :ios => "9.0", :tvos => "9.2" }
   s.source            = { :git => 'https://github.com/react-native-community/react-native-svg.git', :tag => "v#{s.version}" }
+  install_modules_dependencies(s)
 
   if fabric_enabled
     # folly_version must match the version used in React Native
@@ -20,9 +21,35 @@ Pod::Spec.new do |s|
     folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'
 
     s.pod_target_xcconfig = {
-      'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/boost" "$(PODS_ROOT)/boost-for-react-native"  "$(PODS_ROOT)/RCT-Folly"',
+      'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/boost" "$(PODS_ROOT)/boost-for-react-native" "$(PODS_ROOT)/RCT-Folly" "$(PODS_ROOT)/Headers/Public/React-ImageManager/react/renderer/imagemanager"',
       "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
     }
+
+    s.dependency "React-ImageManager"
+    s.dependency "React-utils"
+    s.dependency "React-debug"
+#    s.subspec "xxximagemanager" do |ss|
+#      ss.dependency "React-ImageManager"
+#      ss.source_files         = "react/renderer/imagemanager/**/*.{cpp,h}"
+#      ss.header_dir           = "react/renderer/imagemanager/"
+#      ss.pod_target_xcconfig  = { "HEADER_SEARCH_PATHS" => "\"${PODS_CONFIGURATION_BUILD_DIR}/React-ImageManager/React_ImageManager.framework/Headers\"" }
+#    end
+
+    s.subspec "xxxdebug" do |ss|
+      ss.dependency "ReactCommon"
+      ss.dependency "React-debug"
+      ss.source_files         = "react/debug/**/*.{cpp,h}"
+      ss.header_dir           = "react/debug"
+      ss.pod_target_xcconfig  = { "HEADER_SEARCH_PATHS" => "\"${PODS_CONFIGURATION_BUILD_DIR}/React-debug/React_debug.framework/Headers\"" }
+    end
+
+    s.subspec "xxxutils" do |ss|
+      ss.dependency "ReactCommon"
+      ss.dependency "React-utils"
+      ss.source_files         = "react/utils/**/*.{cpp,h}"
+      ss.header_dir           = "react/utils"
+      ss.pod_target_xcconfig  = { "HEADER_SEARCH_PATHS" => "\"${PODS_CONFIGURATION_BUILD_DIR}/React-utils/React_utils.framework/Headers\"" }
+    end
     s.platforms       = { ios: '11.0', tvos: '11.0' }
     s.compiler_flags  = folly_compiler_flags + ' -DRCT_NEW_ARCH_ENABLED'
     s.source_files    = 'apple/**/*.{h,m,mm,cpp}'
diff --git a/node_modules/react-native-svg/common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.h b/node_modules/react-native-svg/common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.h
index d06bcd4..03bb2c7 100644
--- a/node_modules/react-native-svg/common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.h
+++ b/node_modules/react-native-svg/common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.h
@@ -48,7 +48,8 @@ class JSI_EXPORT RNSVGImageShadowNode final : public ConcreteViewShadowNode<
       ShadowNodeFamilyFragment const &familyFragment,
       ComponentDescriptor const &componentDescriptor) {
     auto imageSource = ImageSource{ImageSource::Type::Invalid};
-    return {imageSource, {imageSource, nullptr}};
+      return {imageSource, {imageSource, nullptr, SharedFunction<>(nullptr)}};
+    // return {imageSource, {imageSource, nullptr}};
   }
 
 #pragma mark - LayoutableShadowNode
```

**Comment by billnbell** [comment]
I have React-ImageManager as a static library in my Podfile, but you could uncomment out above and get rid of that.

```
$static_library += [
   'React',
   'RNBootSplash',
   'Google-Maps-iOS-Utils',
   'GoogleMaps',
   'react-native-maps',
   'react-native-google-maps',
   'react-native-app-auth',
   'React-hermes',
   'React-ImageManager',
   # 'react-native-pdf',
   'react-native-safe-area-context',
   'RNSafeAreaContext'
  ]

  pre_install do |installer|
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
      installer.pod_targets.each do |pod|
        bt = pod.send(:build_type)
        if $static_library.include?(pod.name)
          puts "Overriding the build_type to static_library from static_framework for #{pod.name}"
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
      installer.pod_targets.each do |pod|
        bt = pod.send(:build_type)
        puts "#{pod.name} (#{bt})"
        puts "  linkage: #{bt.send(:linkage)} packaging: #{bt.send(:packaging)}"
      end
  end
```

**Comment by WoLewicki** [comment]
Closing since v13.10.0 (https://github.com/software-mansion/react-native-svg/releases/tag/v13.10.0) has been released and it should be fixed there :rocket:

**Comment by timothyerwin** [comment]
I'm still seeing this problem in 13.10.0 with new arch and fabric enabled

**Comment by timothyerwin** [comment]
after further investigation by reviewing the react native module I discovered the files have been moved around. this is the new path that works:

```
#import <react/renderer/imagemanager/platform/ios/react/renderer/imagemanager/RCTImagePrimitivesConversions.h>
```

**Comment by nonam4** [comment]
i'm also having same issue on rn 0.72.3 and rnsvg at 13.12.0

**Comment by dravecky** [comment]
same issue RN 0.7.2.4 RNSVG 13.13.0

my pod install command
"pod-install": "cd ios && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install --repo-update",

and after run ios i got same issue

**Comment by AlirezaHadjar** [comment]
Hey @WoLewicki 👋 
I'm facing the same issue. Just created a reproduction of the error [here](https://github.com/AlirezaHadjar/react-native-svg-error-reproduction). let me know if you need more info. 

P.S. You should `pod install` with `newArch = enabled`. you can use the `script` I have put in my `package.json` called `pod-install`

**Comment by vksgautam1986** [comment]
having the issue for latest version also with 0.72.4

**Comment by vladimirevstratov** [comment]
The same issue guys

**Comment by Yurii-Lutsyk** [comment]
The same issue(

**Comment by viktorstrate** [comment]
I have the same issue using RN 0.72.4 and SVG 13.14.0. Commenting out the line lets me build the app and it seems to work (at least on iOS) as a temporary solution.

Hope this issue will be reopened and addressed.

**Comment by AlirezaHadjar** [comment]
This issue should be opened again as it is broken. @WoLewicki can you please reopen the issue. I have put a reproducible repo of the issue above.

**Comment by WoLewicki** [comment]
Can you check if #2175 solves the issue?

**Comment by wkwyatt** [comment]
It did not work for me

**Comment by WoLewicki** [comment]
@wkwyatt can you post a repository where it is shown that it does not work?

**Comment by wkwyatt** [comment]
@WoLewicki  The headers you removed in the PR 
https://github.com/software-mansion/react-native-svg/pull/2175

are back in the build 
https://github.com/software-mansion/react-native-svg/blob/1868f00f2012488fdc23d1e4adfafebc97e937be/apple/Elements/RNSVGImage.mm#L35

**Comment by alexanderoskin** [comment]
> @WoLewicki The headers you removed in the PR #2175
> 
> are back in the build
> 
> https://github.com/software-mansion/react-native-svg/blob/1868f00f2012488fdc23d1e4adfafebc97e937be/apple/Elements/RNSVGImage.mm#L35-L36
> 
> Thats in the 14.0.0 tag

@WoLewicki can confirm this. Still the issue with 14.0.0 version

**Comment by WoLewicki** [comment]
This commit landed after the 14.0.0 so it is natural that it is not present in that release 😅 I'll do a release with this change tomorrow 🚀

**Comment by RP-alissonpaschoal** [comment]
It worked here removing these two lines. @WoLewicki do you know when it will be released? For now I made a patch to work.

**Comment by WoLewicki** [comment]
14.1.0 is here :tada: https://github.com/software-mansion/react-native-svg/releases/tag/v14.1.0
