### ISSUE TITLE
iOS Compile fails on react native 0.78.0

### ISSUE THREAD

**Issue by jonluca** [software-mansion/react-native-svg#2635]
### Description

The module fails to compile - ` Compiling react-native-svg Pods/RNSVG » RNSVGGroup.mm`

```
The following build commands failed:
	CompileC /Users/expo/Library/Developer/Xcode/DerivedData/Weights-dqqzqcrfobomtkdpsjeqmpbzsjar/Build/Intermediates.noindex/ArchiveIntermediates/Weights/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/RNSVG.build/Objects-normal/arm64/RNSVGLayoutableShadowNode.o /Users/expo/workingdir/build/node_modules/react-native-svg/common/cpp/react/renderer/components/rnsvg/RNSVGLayoutableShadowNode.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNSVG' from project 'Pods')
Error: The "Run fastlane" step failed because of an error in the Xcode build process. We automatically detected following errors in your Xcode build logs:
- no viable conversion from 'StyleLength' to 'Style::SizeLength' (aka 'facebook::yoga::StyleSizeLength')
- no viable conversion from 'StyleLength' to 'Style::SizeLength' (aka 'facebook::yoga::StyleSizeLength')
Refer to "Xcode Logs" below for additional, more detailed logs.
```

### Steps to reproduce

Attempt to build an IOS project on RN 0.78.0 with the new architecture and the latest version of react-native-svg

### Snack or a link to a repository

https://snack.expo.dev/@jonluca/svg-fail

### SVG version

15.11.1

### React Native version

0.78.0

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by erie-e9** [comment]
+1

**Comment by jakex7** [comment]
Hey! Thanks for reporting this issue. I've merged support for `react-native@0.78.0` in #2619 and will release it as soon as possible.

**Comment by hungcuongDev** [comment]
Are there any new updates on the issue yet? I'm still getting this error when updating to RN 0.78.0

**Comment by okaybeydanol** [comment]
I'm also getting the same error RN 0.78.0. I'm waiting for your new release to continue my project. I hope you can release it as soon as possible.

**Comment by anhtuanMDev** [comment]
Same problem but with android, hope the new version came out soon

**Comment by okaybeydanol** [comment]
When I got an error on iOS, I didn’t even try Android 😅

**Comment by Skaff02** [comment]
Same problem, I hope it doesn't take too much time to get fixed

**Comment by mtnt** [comment]
you can change 
```
#if REACT_NATIVE_MINOR_VERSION >= 77
  style.setDimension(yoga::Dimension::Width, yoga::StyleLength::points(0));
  style.setDimension(yoga::Dimension::Height, yoga::StyleLength::points(0));
```
to 
```
#if REACT_NATIVE_MINOR_VERSION >= 77
  style.setDimension(yoga::Dimension::Width, yoga::Style::SizeLength::points(0));
  style.setDimension(yoga::Dimension::Height, yoga::Style::SizeLength::points(0));
```

I have no idea if it is correct, but it helps to build an app =)

**Comment by irmakcosarsahna** [comment]
Thanks, it's a temporary fix, but we need a permanent update.

> you can change
> 
> ```
> #if REACT_NATIVE_MINOR_VERSION >= 77
>   style.setDimension(yoga::Dimension::Width, yoga::StyleLength::points(0));
>   style.setDimension(yoga::Dimension::Height, yoga::StyleLength::points(0));
> ```
> 
> to
> 
> ```
> #if REACT_NATIVE_MINOR_VERSION >= 77
>   style.setDimension(yoga::Dimension::Width, yoga::Style::SizeLength::points(0));
>   style.setDimension(yoga::Dimension::Height, yoga::Style::SizeLength::points(0));
> ```
> 
> I have no idea if it is correct, but it helps to build an app =) just a workaround

**Comment by hari-mohan-choudhary** [comment]
I am also getting this issue on android on react-native 0.78.0

<img width="1441" alt="Image" src="https://github.com/user-attachments/assets/aa8c72cc-91d5-4778-bac1-49fbbfb1c4c4" />

**Comment by jakex7** [comment]
Hey everyone! Version `15.11.2` supporting `react-native@0.78`, has been released. Thanks for your patience! If you have any issues with the upgrade, feel free to ping me here or open a new issue.
